'use client'

import { FormEvent, useState } from 'react'
import { ArrowUpRight, CheckCircle2, Heart, ShieldCheck } from 'lucide-react'
import { Shell } from './feloga-site'

const amounts = [5000, 10000, 25000, 50000]
export function DonationPage() {
  const [amount, setAmount] = useState('10000'); const [status, setStatus] = useState<'idle'|'loading'|'error'|'success'>('idle'); const [message, setMessage] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus('loading'); setMessage(''); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch('/api/don', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({...data, amount}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (result.paymentUrl) window.location.href = result.paymentUrl; else setStatus('success') } catch (error) { setStatus('error'); setMessage(error instanceof Error ? error.message : 'Le paiement n’a pas pu être préparé.') } }
  return <Shell><section className="donation-hero"><div><span className="eyebrow">Soutenir FELOGA</span><h1>Votre soutien donne<br /><em>une voix à l’avenir.</em></h1><p>Chaque contribution aide FELOGA à ouvrir des espaces de parole, former des jeunes et faire grandir des clubs d’éloquence au Gabon.</p></div><div className="donation-mark"><Heart size={30}/><strong>Donner.<br/>Transmettre.<br/>Transformer.</strong></div></section><section className="donation-layout"><div className="donation-copy"><span className="eyebrow">Pourquoi donner ?</span><h2>Un geste simple, un impact concret.</h2><p>Votre don contribue directement à l’accès aux ateliers, à l’accompagnement des établissements et au déploiement des programmes FELOGA dans de nouvelles villes.</p><div className="donation-benefits"><div><b>01</b><span><strong>Former</strong><small>Des jeunes capables de prendre la parole et d’agir.</small></span></div><div><b>02</b><span><strong>Équiper</strong><small>Des clubs et espaces de débat durables.</small></span></div><div><b>03</b><span><strong>Étendre</strong><small>Nos programmes à davantage de territoires.</small></span></div></div></div><form className="donation-card" onSubmit={submit}><span className="eyebrow">Faire un don</span><h2>Choisissez votre contribution</h2><div className="amounts">{amounts.map((value) => <button type="button" className={amount === String(value) ? 'amount active' : 'amount'} onClick={() => setAmount(String(value))} key={value}>{value.toLocaleString('fr-FR')} FCFA</button>)}</div><label className="form-field"><span>Ou indiquez un montant (FCFA) <b>*</b></span><input type="number" min="1000" step="500" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><div className="donor-grid"><label className="form-field"><span>Nom complet</span><input name="name" placeholder="Votre nom" /></label><label className="form-field"><span>Email</span><input name="email" type="email" placeholder="vous@exemple.com" required /></label></div><p className="payment-note"><ShieldCheck size={17}/> Paiement sécurisé par Airtel Money, Moov Money, Visa ou Mastercard via notre agrégateur.</p>{status === 'error' && <p className="form-error" role="alert">{message}</p>}{status === 'success' && <p className="success-note"><CheckCircle2 size={17}/> Merci pour votre soutien.</p>}<button className="button button-primary donation-submit" disabled={status === 'loading'} type="submit">{status === 'loading' ? 'Préparation…' : 'Continuer vers le paiement'} <ArrowUpRight size={16}/></button><small className="donation-footnote">Vous serez redirigé vers la page de paiement sécurisée.</small></form></section></Shell>
}
  
