'use client'

import { useMemo, useState } from 'react'
import { ArrowUpRight, X } from 'lucide-react'
import { Footer } from './feloga-site'
import { Header } from './feloga-header'

type Article = { id: number; category: string; date: string; readTime: string; title: string; excerpt: string; body: string; accent: string; symbol: string }

const articles: Article[] = [
  { id: 1, category: 'Événements', date: '15 septembre 2026', readTime: '4 min', title: 'Gestion de Crise Tour : apprendre à agir quand tout s’accélère', excerpt: 'Le 31 octobre 2026, FELOGA Seed ouvre sa saison avec une journée consacrée à la crise, au leadership et à l’intelligence collective.', body: 'Une crise révèle autant la solidité d’un collectif que sa capacité à écouter. Le Gestion de Crise Tour propose une journée de conférences, de mises en situation et d’échanges pour apprendre à lire une situation complexe, structurer une réponse et prendre la parole avec justesse.', accent: '#0b5b4c', symbol: '↗' },
  { id: 2, category: 'Programmes', date: '14 septembre 2026', readTime: '5 min', title: 'FELOGA Seed : de la prise de parole à la contribution', excerpt: 'Après une année d’initiations, une nouvelle saison s’ouvre pour révéler les potentiels et faire grandir les leaders de demain.', body: 'FELOGA Seed relie éloquence, leadership, émancipation et intelligence collective afin que chaque participant puisse structurer sa pensée, écouter les autres et contribuer à son environnement.', accent: '#18a982', symbol: '✦' },
  { id: 3, category: 'Point de vue', date: '08 septembre 2026', readTime: '3 min', title: 'Pourquoi la parole est une compétence d’émancipation', excerpt: 'S’exprimer avec clarté, c’est aussi apprendre à se situer, défendre ses droits et prendre part aux décisions.', body: 'La prise de parole permet de nommer une expérience, de défendre une idée et de créer du lien. Pour FELOGA, elle renforce la confiance et donne une place dans le débat public.', accent: '#d18e49', symbol: '◌' },
  { id: 4, category: 'Communauté', date: '28 août 2026', readTime: '4 min', title: 'Les clubs, premiers laboratoires de l’intelligence collective', excerpt: 'Dans les clubs associés, la pratique régulière transforme les différences de points de vue en force commune.', body: 'Un club d’éloquence est un espace de pratique et de transmission. On y apprend à argumenter, à recevoir un retour, à changer de perspective et à faire progresser les autres.', accent: '#6d8f7e', symbol: '◎' },
  { id: 5, category: 'Presse', date: '20 août 2026', readTime: '2 min', title: 'FELOGA, des voix émergentes pour un Gabon plus dialoguant', excerpt: 'La Fédération d’Éloquence Gabonaise met en réseau les initiatives qui font de la parole un levier d’avenir.', body: 'FELOGA rassemble les acteurs de l’éloquence et crée des passerelles entre jeunes, établissements, institutions et partenaires.', accent: '#274f45', symbol: '●' },
]
const categories = ['Toutes', ...Array.from(new Set(articles.map((article) => article.category)))]

export function NewsPage() {
  const [category, setCategory] = useState('Toutes')
  const [selected, setSelected] = useState<Article | null>(null)
  const filtered = useMemo(() => category === 'Toutes' ? articles : articles.filter((article) => article.category === category), [category])
  return <><Header /><main><div className="news-page"><section className="news-library-hero"><div><span className="eyebrow">Actualités & presse</span><h1>Les voix qui<br /><em>font mouvement.</em></h1><p>Articles, récits de terrain et points de vue pour suivre les idées et les actions de FELOGA.</p></div><div className="news-library-mark"><span>05</span><small>ARTICLES<br />À EXPLORER</small></div></section><section className="news-library"><div className="news-editorial-lede"><span className="eyebrow">Journal FELOGA · 2026</span><h2>Comprendre, transmettre, mettre en mouvement.</h2><p>Nos actualités donnent à voir les idées, les pratiques et les personnes qui construisent une société plus dialoguante.</p></div><div className="news-toolbar"><div><span className="eyebrow">Le fil FELOGA</span><h2>À lire maintenant</h2><p className="news-count">{filtered.length} article{filtered.length > 1 ? 's' : ''} dans la sélection</p></div><div className="news-filters" role="tablist" aria-label="Filtrer les articles">{categories.map((item) => <button key={item} type="button" className={category === item ? 'active' : ''} onClick={() => setCategory(item)} role="tab" aria-selected={category === item}>{item}</button>)}</div></div><div className="article-grid">{filtered.map((article, index) => <button type="button" className={`article-card ${index === 0 ? 'article-card-featured' : ''}`} key={article.id} onClick={() => setSelected(article)}><span className="article-card-art" style={{ background: `linear-gradient(135deg, ${article.accent}, #07342c)` }}><b>{String(article.id).padStart(2, '0')}</b><i aria-hidden="true">{article.symbol}</i></span><span className="article-meta"><span>{article.category}</span><span>{article.date}</span></span><h3>{article.title}</h3><p>{article.excerpt}</p><span className="article-read">Lire l’article <ArrowUpRight size={15} /></span></button>)}</div></section></div></main><Footer />{selected && <div className="article-modal-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="article-modal" role="dialog" aria-modal="true" aria-labelledby="article-title" onClick={(event) => event.stopPropagation()}><button className="article-close" type="button" aria-label="Fermer l’article" onClick={() => setSelected(null)}><X size={18} /></button><div className="article-modal-meta"><span>{selected.category}</span><span>·</span><span>{selected.date}</span><span>·</span><span>{selected.readTime}</span></div><h2 id="article-title">{selected.title}</h2><p className="article-lede">{selected.excerpt}</p><p>{selected.body}</p></article></div>}</> 
}
