'use client'

import { useState } from 'react'
import { CalendarDays, Check, ChevronRight, Heart, Users, Building2, ArrowUpRight } from 'lucide-react'
import { Button, Shell } from './feloga-site'

const events = [
  { month: 'OCT', day: '31', year: '2026', title: 'Gestion de Crise Tour', type: 'Événement phare', place: 'Institut Français du Gabon · Libreville', text: 'Une journée pour apprendre à anticiper la crise, prendre la parole avec justesse et mobiliser une intelligence collective.', href: '/evenements-competitions/gestion-de-crise-tour' },
  { month: 'NOV', day: '14', year: '2026', title: 'Atelier · Prendre la parole', type: 'Atelier', place: 'Libreville · Sur inscription', text: 'Un format pratique pour structurer ses idées, s’exprimer avec clarté et gagner en assurance.', href: '/programmes-formations/art-oratoire' },
  { month: 'DÉC', day: '05', year: '2026', title: 'Rencontre des clubs FELOGA', type: 'Communauté', place: 'Libreville · Membres et partenaires', text: 'Un temps de partage entre clubs, facilitateurs et partenaires pour préparer la suite du réseau.', href: '/nous-rejoindre/adhesion' },
]

export function AgendaPage() {
  const [filter, setFilter] = useState('Tous')
  const filters = ['Tous', 'Événements phares', 'Ateliers', 'Communauté']
  const visible = events.filter((event) => filter === 'Tous' || event.type === filter.slice(0, -1))
  return <Shell><section className="agenda-hero"><div><span className="eyebrow">Événements · Agenda</span><h1>Les rendez-vous<br /><em>qui mettent en mouvement.</em></h1><p>Conférences, ateliers et rencontres : retrouvez les prochaines occasions d’apprendre, de dialoguer et d’agir avec FELOGA.</p></div><div className="agenda-calendar-mark"><CalendarDays size={27} /><strong>2026</strong><span>SAISON DE<br />CONTRIBUTION</span></div></section><section className="agenda-wrap"><div className="agenda-heading"><div><span className="eyebrow">Calendrier FELOGA</span><h2>Prochains rendez-vous</h2></div><div className="agenda-filters" role="group" aria-label="Filtrer les événements">{filters.map((item) => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="agenda-list">{visible.map((event) => <article className="agenda-event" key={event.title}><div className="agenda-date"><span>{event.month}</span><strong>{event.day}</strong><small>{event.year}</small></div><div className="agenda-event-body"><span className="agenda-type">{event.type}</span><h3>{event.title}</h3><p>{event.text}</p><div className="agenda-place">{event.place}</div></div><Button href={event.href} variant="text">Voir le rendez-vous</Button></article>)}</div></section><section className="agenda-cta"><div><span className="eyebrow">Votre territoire, votre public</span><h2>Accueillir un événement FELOGA.</h2><p>Vous souhaitez organiser un atelier, une rencontre ou une étape du Tour ? Construisons un format adapté à votre communauté.</p></div><Button href="/contact">Proposer un rendez-vous</Button></section></Shell>
}

const ways = [
  { icon: Users, number: '01', title: 'Rejoindre la communauté', text: 'Participez aux activités, intégrez un club et développez votre voix au contact d’autres jeunes engagés.', href: '/nous-rejoindre/adhesion', label: 'Adhérer à FELOGA' },
  { icon: Building2, number: '02', title: 'Créer un partenariat', text: 'Écoles, entreprises, institutions et médias : mettons vos ressources au service de parcours qui transforment.', href: '/nous-rejoindre/partenariats', label: 'Devenir partenaire' },
  { icon: Heart, number: '03', title: 'Soutenir une action', text: 'Votre soutien rend les ateliers accessibles, accompagne les clubs et donne plus de portée aux voix émergentes.', href: '/faire-un-don', label: 'Faire un don' },
]

const galleryItems = [
  ['01', 'Ateliers', 'Des espaces pour pratiquer, écouter et progresser.', '#0b5b4c'],
  ['02', 'Prise de parole', 'Les voix émergentes prennent leur place.', '#18a982'],
  ['03', 'Communauté', 'Des rencontres qui créent des liens durables.', '#d18e49'],
  ['04', 'Gestion de crise', 'Apprendre ensemble à répondre aux situations complexes.', '#274f45'],
  ['05', 'FELOGA Seed', 'Une saison de contribution et de transformation.', '#6d8f7e'],
  ['06', 'Partenaires', 'Une intelligence collective en mouvement.', '#0e6d59'],
]

export function GalleryPage() { return <Shell><section className="gallery-hero"><div><span className="eyebrow">Événements · Galerie médias</span><h1>Tous nos moments,<br /><em>en mouvement.</em></h1><p>Ateliers, rencontres, prises de parole et temps forts : une collection vivante de la communauté FELOGA.</p></div><div className="gallery-hero-mark">06<br /><small>RÉCITS<br />EN IMAGES</small></div></section><section className="gallery-wall"><div className="gallery-heading"><span className="eyebrow">La vie FELOGA</span><h2>Des images de travail, de lien et de transmission.</h2><p>Chaque image raconte une manière d’apprendre ensemble et de faire de la parole une capacité d’action.</p></div><div className="gallery-grid">{galleryItems.map(([number, title, text, color], index) => <article className={`gallery-tile gallery-tile-${index + 1}`} key={number} style={{ background: `linear-gradient(145deg, ${color}, #07342c)` }}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><b aria-hidden="true">{index % 2 ? '✦' : '◌'}</b></article>)}</div></section><section className="gallery-cta"><div><span className="eyebrow">Vous étiez là ?</span><h2>Partager un souvenir FELOGA.</h2><p>Photographe, participant ou partenaire, envoyez-nous vos images et le contexte de leur prise.</p></div><Button href="/contact">Nous transmettre un média</Button></section></Shell> }

export function JoinPage() { return <Shell><section className="join-new-hero"><div><span className="eyebrow">Nous rejoindre · Faire grandir les voix</span><h1>Soutenir FELOGA,<br /><em>c’est investir dans l’avenir.</em></h1><p>Rejoindre FELOGA, c’est choisir de faire de la parole un outil d’émancipation citoyenne. Par une adhésion, un partenariat, un don ou un engagement bénévole, vous rendez les parcours de jeunes plus accessibles et plus durables.</p><div className="hero-actions"><Button href="/nous-rejoindre/adhesion">Commencer mon parcours</Button><Button href="/contact" variant="outline">Parler à FELOGA</Button></div></div><div className="join-new-stamp"><span>Votre soutien</span><strong>fait<br />grandir<br />une voix.</strong></div></section><section className="join-story"><div className="join-story-label"><span>Une histoire, comme tant d’autres</span><b>01</b></div><div><h2>Quand une voix trouve sa place, tout un avenir s’ouvre.</h2><p>Elle a des idées mais n’ose jamais lever la main. À son premier atelier, elle apprend à structurer ce qu’elle veut dire. Ça tremble encore, mais ça sort. C’est le début d’une place qu’elle ose enfin prendre.</p><p>Elle rencontre d’autres jeunes, découvre des points de vue différents et comprend que sa voix compte dans les discussions qui la concernent. Aujourd’hui, elle porte un projet, interpelle, propose. Elle est devenue actrice du changement.</p></div></section><section className="join-reasons"><div className="join-reasons-heading"><span className="eyebrow">Trois façons de prendre part</span><h2>Une place pour chaque engagement.</h2></div><div className="join-way-grid">{ways.map(({ icon: Icon, ...way }) => <article key={way.number}><div className="join-way-top"><span>{way.number}</span><Icon size={25} /></div><h3>{way.title}</h3><p>{way.text}</p><Button href={way.href} variant="text">{way.label}</Button></article>)}</div></section><section className="join-impact"><span className="eyebrow">Un besoin social et sociétal</span><h2>Les jeunes d’aujourd’hui seront les adultes qui répondront aux grands défis de demain.</h2><p>Donner dès maintenant les moyens de prendre la parole et de construire des ponts, c’est investir directement dans la société qui vient.</p></section></Shell> }
